// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYZoiO_1gKfLy5_cgHUXL7WX1bprczzNs',
    appId: '1:657920169419:web:383620c47622ca6274124e',
    messagingSenderId: '657920169419',
    projectId: 'dice-multiplayer-game',
    authDomain: 'dice-multiplayer-game.firebaseapp.com',
    storageBucket: 'dice-multiplayer-game.firebasestorage.app',
    measurementId: 'G-ZSKF5XNKDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCGi2mec5lVsjwVOIjyFS7Kx_QFO_uO3I',
    appId: '1:657920169419:android:e596b488b3094fac74124e',
    messagingSenderId: '657920169419',
    projectId: 'dice-multiplayer-game',
    storageBucket: 'dice-multiplayer-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG3aaxdJQcrO0hlYlVUsDIir9384Bcek4',
    appId: '1:657920169419:ios:ce445e4c3d31a2d574124e',
    messagingSenderId: '657920169419',
    projectId: 'dice-multiplayer-game',
    storageBucket: 'dice-multiplayer-game.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
